### ISSUE TITLE
The plugin doesn't work anymore

### ISSUE THREAD

**Issue by Emasoft** [mancuniancol/plugin.video.haruhichan#1]
The plugin doesn't work anymore. It just return 0 results each time for every category. Maybe something changed on the Haruhichan page?

**Comment by mancuniancol** [comment]
You are right,  Haruhichan disabled the API.  

http://ptp.haruhichan.com/list.php?type=all&genres=&sort=rank&page=1&limit=100&order=asc

It is giving 403 error.  Then, I have not way to have the information.  Sorry.
